### ISSUE TITLE
Autocomplete is missing context after typing a dot

### ISSUE THREAD

**Issue by bigardone** [elm-tooling/elm-language-server#211]
While typing `Htm`, the autocomplete popup lists all `Html` functions.

![image](https://user-images.githubusercontent.com/1090272/73588653-f5bbd900-44cb-11ea-8da0-f69863344f61.png)

However, once you type the `.`, it does not list `Html` functions anymore.

![image](https://user-images.githubusercontent.com/1090272/73588670-2b60c200-44cc-11ea-8ff5-8a705c1b274f.png)

## Expected Behavior
List all related functions belonging to the preceding typed module.

## Current Behavior
It does not list anything related to the preceding module. It looks like it loses the context.

## Steps to Reproduce (for bugs)
1. Open an Elm file with imported modules.
2. Start typing the name of an import and check how it displays functions.
3. Type the `.` and check how the previously listed functions disappear.

## Context
Just trying to list all the functions of a given module while typing.

## Your Environment
* Version used: elm-language-server@1.5.0
* Editor used: neovim + coc
* Environment name and version (e.g. node.js 5.4): node v12.13.0
* Operating System and version: macOS Catalina

**Comment by Razzeee** [comment]
Your importing `Html` above, correct?

This seems to work fine in VSCode, so it might be an implementation detail in coc? Can you open a ticket on their side and CC me? (or VSCode is not following the standard)

**Comment by Augustin82** [comment]
Same issue here.
Version used: elm-language-server@1.4.6
Editor used: neovim + coc
Environment name and version (e.g. node.js 5.4): node v10.18.1
Operating System and version: Ubuntu 18.04

**Comment by ErikFeeley** [comment]
I have noticed this same behavior!

Interestingly when you leave out the dot the module based completion works for coc + nvim. For example. `Cmd.map` brought up all kinds of suggestions that do not make sense. However `Cmdmap` by itself only suggested `Cmd.map`!

**Comment by NikosEfthias** [comment]
I use Ale instead of coc and I have the same issue here

**Comment by Razzeee** [comment]
I guess we need to raise/talk with the CoC/Ale people, if their implementation is correct, or if we need to talk to VSCode to align. Can somebody create a ticket at CoC?

**Comment by bigardone** [comment]
@Razzeee I'll create the ticket between today and tomorrow :)

**Comment by bigardone** [comment]
@Razzeee done, I hope it helps :)

**Comment by oblitum** [comment]
I think this seems like a VSCode issue instead. After you type `.` you get code automatically pre-selected? If that's happening, the server is sending a preferred item for pre-selection, and coc.nvim is obeying the server, if this is not happening on VSCode, then it's another detail VSCode is ignoring from server. On a side note, Microsoft driven protocols are a mess, no difference here.

**Comment by oblitum** [comment]
IMO issue tracker on other plugin shouldn't get noise until this is figured out here at the origin. If you open an issue on coc.nvim, that means you'll also should on ALE or any server with same behavior except VSCode. I think that should not happen before the problem had actually figured out to point these client's author what in they protocol is not being followed, just asking them to look it up because VSCode alone is behaving some way isn't great.

**Comment by Razzeee** [comment]
Unfortunatly VSCode is the reference implementation... 

So I think it's fair to think that the reference is correct, but I guess we can ask @dbaeumer what he thinks.

**Comment by oblitum** [comment]
VSCode shouldn't be taken as a standard on that matter because the protocol features are being essentially _driven_ (after the fact) by VSCode's behavior, but the protocol spec can lag behind VSCode behavior until their changes get incorporated/published to the protocol. Due to that, it's fair to state that VSCode "implementation" (it's actually kind the reverse) should be taken with a grain of salt. In the sense that, if you stick to replicating it, you may end up not following the last released protocol at some point.

See [such discussion](https://github.com/microsoft/language-server-protocol/issues/640#issuecomment-449407046) and others for example.

**Comment by bigardone** [comment]
@Razzeee https://github.com/neoclide/coc.nvim/issues/1530#issuecomment-586261989 🤷‍♂

**Comment by Razzeee** [comment]
I guess we need to provide him a log?

**Comment by Razzeee** [comment]
This has been fixed in CoC now and should be included in the next coc version. I think we should raise an issue on ALE too?

**Comment by jc00ke** [comment]
I just updated CoC to `0.0.77-817efd5108` and I'm still seeing this issue.
![coc-elm](https://user-images.githubusercontent.com/18191/78467751-a741db00-76c4-11ea-814e-ba5979d0fade.gif)

**Comment by Razzeee** [comment]
@jc00ke that version is still to old to include https://github.com/neoclide/coc.nvim/commit/af2b7f55843bbb8e3d6a1fc9c41e7f7a54d3b27d as far as I can tell

**Comment by jc00ke** [comment]
Ah, because I'm running off the `release` branch... missed that. Looks like `v0.0.78` is being cut right now.

**Comment by jc00ke** [comment]
![Peek 2020-04-10 11-24](https://user-images.githubusercontent.com/18191/79013531-cfdf3000-7b1d-11ea-9b35-2e6d0f9ed0e4.gif)

LGTM!

**Comment by bigardone** [comment]
Yeah! working fine to me too 🎉 
Closing the issue :)
