### ISSUE TITLE
Test dependencies are ignored / not implemented

### ISSUE THREAD

**Issue by andys8** [elm-tooling/elm-language-server#47]
# Issue

> UNKNOWN IMPORT - The MainTest module has a bad import:      import Test  I cannot find that module! Is there a typo in the module name?  The "source-directories" field of your elm.json tells me to only look in the src directory, but it is not there. Maybe it is in a package that is not installed yet?

# Cause

Currently direct dependencies are read, but `test-dependencies` are not. This will lead to 

https://github.com/elm-tooling/elm-language-server/blob/e43252ac8027e678cb6e0377f9f42fafe274344b/src/providers/astProvider.ts#L89-L92

## elm.json Structure
```json
    "dependencies": {
        "direct": {
        },
        "indirect": {
        }
    },
    "test-dependencies": {
        "direct": {
        },
        "indirect": {
        }
    }

```

# Solution

For now it's probably an improvement to add `test-dependencies`. In the long term there needs to be some distinction between dependency types, to disallow importing test dependencies in source files.

**Comment by andys8** [comment]
I started looking into it. My initial thought is, it should look something like this, which is not working:
https://github.com/elm-tooling/elm-language-server/commit/5de27ba5ad32dd2801c2ccf4506b6c1a78717bd9

I haven't figured out, how to debug, using the language server typescript code base, and vim with ale.
It looks like debugging is not well supported (https://github.com/w0rp/ale/issues/2137)

**Comment by Razzeee** [comment]
Please try again, should work now, if you got the same problems that I could find with the spa example

**Comment by andys8** [comment]
https://github.com/rtfeldman/elm-spa-example/blob/master/tests/RoutingTests.elm

Still getting the same error in the first line claiming it can't find `Test` as an import. 

![image](https://user-images.githubusercontent.com/13085980/58791886-59b39800-85f3-11e9-9798-21360360096b.png)

Same behavior with my project. Is it working for you?

**Comment by Razzeee** [comment]
Well I made completions, hover, references work yesterday. I can reprod it, will look at it later. I would guess it's caused by us trying to run `elm make` on it for some reason, but we should be running `elm test`.

**Comment by andys8** [comment]
@Razzeee Maybe this implementation is a good help. https://github.com/w0rp/ale/blob/a730a6d5d5a434f3ec93b77a4e003272a9e22925/ale_linters/elm/make.vim#L227

It is consistent with your thoughts.

**Comment by andys8** [comment]
I replaced `elm` with `elm-test` for testing and it seems to work pretty well. The error message is gone and compile checks are working fine.

1. `elmTestPath` param.
2. Logic to determine if `elm` or `elm-test` should be used for compilation. Compare: https://github.com/w0rp/ale/blob/a730a6d5d5a434f3ec93b77a4e003272a9e22925/ale_linters/elm/make.vim#L178

**Comment by Razzeee** [comment]
Closing, as it should be working for now.

**Comment by andys8** [comment]
Yep, can confirm it's working
